- alias: 'Camera command'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/camera'
  action:
  - service: notify.homemyassistant_bot
    data:
      message: 'R2 Salone - Snapshot'
  - service: script.camera_snapshot