- alias: 'Telegram Start Command'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/start'
  action:
  - service: notify.homemyassistant_bot
    data:
      message: 'Di seguito la lista dei Comandi disponibili'
      data:
        keyboard:
          - '/my, /person'
          - '/ping, /camera'
          - '/start'