####################################################
#                                                  #
#                    Scenes                        #
#                                                  #
####################################################

####################################################
#                Air Conditioner                   #
####################################################

- alias: AC Mode OFF - Automation
  trigger:
    platform: state
    entity_id: input_select.ac_mode
    to: "Power Off"
  action:
    - service: switch.turn_off
      entity_id: switch.air_conditioner__heat_30
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "AC Mode changed to: {{ trigger.to_state.state }}"

- alias: AC Mode - Hot
  trigger:
    platform: state
    entity_id: input_select.ac_mode
    to: "Hot"
  action:
    - service: switch.turn_on
      entity_id: switch.air_conditioner__heat_30
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "AC Mode  changed to: {{ trigger.to_state.state }}"

- alias: AC Mode - Hot Morning
  trigger:
    platform: state
    entity_id: input_select.ac_mode
    to: "Hot Morning"
  action:
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "AC Mode  changed to: {{ trigger.to_state.state }}"

- alias: AC Mode - Cold
  trigger:
    platform: state
    entity_id: input_select.ac_mode
    to: "Cold"
  action:
    - service: switch.turn_on
      entity_id: switch.air_conditioner__cold_18
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "AC Mode  changed to: {{ trigger.to_state.state }}"

- alias: AC Mode - Cold Morning
  trigger:
    platform: state
    entity_id: input_select.ac_mode
    to: "Cold Morning"
  action:
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "AC Mode  changed to: {{ trigger.to_state.state }}"

- alias: AC Mode - Humidity
  trigger:
    platform: state
    entity_id: input_select.ac_mode
    to: "Himidity"
  action:
    - service: switch.turn_on
      entity_id: switch.air_conditioner__humidity
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "AC Mode  changed to: {{ trigger.to_state.state }}"

- alias: AC Mode - Humidity Morning
  trigger:
    platform: state
    entity_id: input_select.ac_mode
    to: "Humidity Morning"
  action:
    - service: notify.homenicoassistant_bot
      data_template:
        message: >
           "AC Mode  changed to: {{ trigger.to_state.state }}"