- alias: Nico Battery Low - Notification
  trigger:
     platform: time
     # You can also match on interval. This will match every 45 minutes
     minutes: '/45'
     seconds: 00

  condition:
     condition: or
     conditions:
       - condition: template
         value_template: "{{ states.device_tracker.nico_nico.attributes.battery < 30 }}" 

  action:
    - service: notify.homenicoassistant_bot
      data:
        message: "Nico's Telephone is on low Battery at {{ states('sensor.date__time') }}"
    - service: notify.homenicoassistant_bot
      data:
        message: "Nico's Telephone Battery Level is {{ states('sensor.batteria_telefono_nico') }}%"

- alias: Mamma Battery Low - Notification
  trigger:
     platform: time
     # You can also match on interval. This will match every 45 minutes
     minutes: '/45'
     seconds: 00

  condition:
     condition: or
     conditions:
       - condition: template
         value_template: "{{ states.device_tracker.mamma_mamma.attributes.battery < 30 }}"

  action:
    - service: notify.homenicoassistant_bot
      data:
        message: "Mom's Telephone is on low Battery at {{ states('sensor.date__time') }}"
    - service: notify.homenicoassistant_bot
      data:
        message: "Mom's Telephone Battery Level is {{ states('sensor.batteria_telefono_mamma') }}%"