####################################################
#                  Battery                         #
#                Notifications                     #
####################################################

####################################################
#                  my Battery                    #
####################################################

- alias: my Battery Low - Notification
  trigger:
     platform: time
     # You can also match on interval. This will match every 45 minutes
     minutes: '/45'
     seconds: 00

  condition:
     condition: or
     conditions:
       - condition: template
         value_template: "{{ states.device_tracker.my_my.attributes.battery < 30 }}" 

  action:
    - service: notify.homemyassistant_bot
      data:
        message: "my's Telephone is on low Battery at {{ states('sensor.date__time') }}"
    - service: notify.homemyassistant_bot
      data:
        message: "my's Telephone Battery Level is {{ states('sensor.batteria_telefono_my') }}%"

####################################################
#                  person Battery                     #
####################################################

- alias: person Battery Low - Notification
  trigger:
     platform: time
     # You can also match on interval. This will match every 45 minutes
     minutes: '/45'
     seconds: 00

  condition:
     condition: or
     conditions:
       - condition: template
         value_template: "{{ states.device_tracker.person_person.attributes.battery < 30 }}"

  action:
    - service: notify.homemyassistant_bot
      data:
        message: "person's Telephone is on low Battery at {{ states('sensor.date__time') }}"
    - service: notify.homemyassistant_bot
      data:
        message: "person's Telephone Battery Level is {{ states('sensor.batteria_telefono_person') }}%"