####################################################
#                  Hass Start                      #
####################################################

- alias: Home Assistant Start - Notify
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: notify.homenicoassistant_bot
    data:
      message: "Home Assistant Start at {{ states('sensor.date__time') }}"

####################################################
#                  Hass Stop                       #
####################################################

- alias: Home Assistant Stop - Notify
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    service: notify.homenicoassistant_bot
    data:
      message: "Home Assistant Stop at {{ states('sensor.date__time') }}"