####################################################
#                  Zone                            #
#              Notifications                       #
####################################################

####################################################
#                   person  Home                      #
####################################################

- alias: person at Home - Notification
  trigger:
     platform: zone
     event: enter
     zone: zone.home
     entity_id: device_tracker.person_person
  action:
   service: notify.homemyassistant_bot
   data:
     message: "person is at Home at {{ states('sensor.date__time') }}"

####################################################
#                   person Out Home                   #
####################################################

- alias: person Outside Home - Notification
  trigger:
     platform: zone
     event: leave
     zone: zone.home
     entity_id: device_tracker.person_person
  action:
   service: notify.homemyassistant_bot
   data:
     message: "person is going out at {{ states('sensor.date__time') }}"