####################################################
#                   gf  Home                    #
####################################################

- alias: gf at Home - Notification
  trigger:
     platform: state
     entity_id: device_tracker.iphonemarie
     from: 'not_home'
     to: 'home'
  action:
   service: notify.homemyassistant_bot
   data:
     message: "gf is at Home <3 <3 {{ states('sensor.date__time') }}"

####################################################
#               gf out Home                     #
####################################################

- alias: gf Outside Home - Notification
  trigger:
     platform: state
     entity_id: device_tracker.iphonemarie
     from: 'home'
     to: 'not_home'
  action:
   service: notify.homemyassistant_bot
   data:
     message: "gf is going out at {{ states('sensor.date__time') }}"
