####################################################
#                  my Home                       #
####################################################

- alias: my at Home - Notification
  trigger:
     platform: zone
     entity_id: device_tracker.my_my
     zone: zone.home
     event: enter
  condition:
     condition: time
     after: '07:00:00'
     before: '23:59:00'
  action:
   service: notify.homemyassistant_bot
   data:
     message: "my is at Home at {{ states('sensor.date__time') }}"

####################################################
#                  my Out Home                   #
####################################################

- alias: my is going out - Notification
  trigger:
     platform: zone
     entity_id: device_tracker.my_my     
     zone: zone.home
     event: leave
  condition:
     condition: time
     after: '07:00:00'
     before: '23:59:00'         
  action:
   service: notify.homemyassistant_bot
   data:
     message: "my is going out from {{ trigger.to_state.state }} at  {{ states('sensor.date__time') }}"

####################################################
#                  my Dad                        #
####################################################

- alias: my at Papa's Home - Notification
  trigger:
     platform: zone
     event: enter
     zone: zone.papa
     entity_id: device_tracker.my_my
  action:
   service: notify.homemyassistant_bot
   data:
     message: "my is at Papa's Home at {{ states('sensor.date__time') }}"

####################################################
#                  my Out Dad                    #
####################################################

-  alias: my leaving Papa's Home - Notification
   trigger:
      platform: zone
      event: leave
      zone: zone.papa
      entity_id: device_tracker.my_my
   action:
    service: notify.homemyassistant_bot
    data:
      message: "my is going out from Papa's Home {{ states('sensor.date__time') }}"

####################################################
#                  my Work                       #
####################################################

- alias: my at Work - Notification
  trigger:
    platform: zone
    event: enter
    zone: zone.work
    entity_id: device_tracker.my_my
  condition:
    condition: time
    after: '07:00:00'
    before: '20:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  -  service: notify.homemyassistant_bot
     data:
       message: "my at Work at {{ states('sensor.date__time') }}"

####################################################
#                my out Work                     #
####################################################

- alias: my out from Work - Notification
  trigger:
    platform: zone
    event: leave
    zone: zone.work
    entity_id: device_tracker.my_my
  condition:
    condition: time
    after: '07:00:00'
    before: '20:00:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
   - service: notify.homemyassistant_bot
     data:
       message: "my is going out from Work at {{ states('sensor.date__time') }}"