- alias: AC - Hot Morning - ON
  trigger:
    platform: time
    at: '07:30:00'
  condition:
   - condition: time
     weekday:
       - mon
       - tue
       - wed
       - thu
       - fri
   - condition: state
     entity_id: input_select.ac_mode
     state: "Hot Morning"
  action:
    - service: switch.turn_on
      entity_id: switch.air_conditioner__heat_30
    - service: notify.homenicoassistant_bot
      data:
        message: "AC Morning ON - Heat 30 - Automation"

- alias: AC - Cold Morning - ON
  trigger:
    platform: time
    at: '07:30:00'
  condition:
   - condition: time
     weekday:
       - mon
       - tue
       - wed
       - thu
       - fri
   - condition: state
     entity_id: input_select.ac_mode
     state: "Cold Morning"
  action:
    - service: switch.turn_on
      entity_id: switch.air_conditioner__cold_18
    - service: notify.homenicoassistant_bot
      data:
        message: "AC Morning ON - Cold 18 - Automation  {{ trigger.entity_id }} "

- alias: AC - Morning - OFF
  trigger:
    platform: time
    at: '08:00:00'
  condition:
   - condition: time
     weekday:
       - mon
       - tue
       - wed
       - thu
       - fri
  action:
    - service: switch.turn_off
      entity_id: switch.air_conditioner__heat_30
    - service: switch.turn_off
      entity_id: switch.air_conditioner__cold_18
    - service: switch.turn_off
      entity_id: switch.air_conditioner__humidity            
    - service: notify.homenicoassistant_bot
      data:
        message: "AC Morning OFF - Automation. {{ trigger.entity_id }}"